server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  shutdown: graceful
  servlet:
    context-path: /api

spring:
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/auth/.well-known/jwks.json