version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#      - ELASTIC_PASSWORD=password
# $ winpty docker exec -it elasticsearch bin/elasticsearch-service-tokens create elastic/kibana kibana-system
# SERVICE_TOKEN elastic/kibana/kibana-system = AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zeXN0ZW06b1ZCVERfdTZUZnV1UEFiXzVLS0pvQQ
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SSL_VERIFICATION_MODE=none
      - ELASTICSEARCH_SERVICE_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zeXN0ZW06SnBqMHVMT3hUbjZtdVdEYUdvZGRIUQ
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=password

    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge