ecom:
  stripe:
    secret_key: ${STRIPE_SECRET_KEY:00000000000000000000000}
    publishable_key: ${STRIPE_PUBLISHABLE_KEY:00000000000000000000000}
    webhook_secret: ${STRIPE_WHSECRET:whsec_00000000000000000000000000000000}
  razorpay:
    key: ${RAZORPAY_KEY:00000000000000000000000}
    secret_key: ${RAZORPAY_SECRET_KEY:00000000000000000000000}
    webhook_secret: ${RAZORPAY_WHSECRET:whsec_00000000000000000000000000000}
  payment_redirect_url: ${PAYMENT_REDIRECT_URL:http://localhost:8000/payment-redirect}
  kafka:
    topics:
      payment: payment-topic

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  shutdown: graceful
  servlet:
    context-path: /api

spring:
  application:
    name: payment-service
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8000}
          jwk-set-uri: ${AUTH_JWK_ISSUER_URI:http://localhost:8000/user-service/api}/.well-known/jwks.json
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: SSL
      ssl.truststore.type: PEM
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH}
      ssl.keystore.type: PEM
      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    properties:
      security.protocol: PLAINTEXT