services:
  user-database:
    image: mysql:8.1.0
    container_name: user-database
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
  app-vault:
    image: hashicorp/vault:1.19.1
    container_name: app-vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=token
    ports:
      - "8200:8200"