ecom:
  google.client_id: ${GOOGLE_CLIENT_IDENTIFIER:000000000000-00000000000.apps.googleusercontent.com}
  meta.client_id: ${META_CLIENT_IDENTIFIER:000000000000-00000000000}
  microsoft.client_id: ${MICROSOFT_CLIENT_IDENTIFIER:000000000000-00000000000}
  token_duration: ${TOKEN_DURATION_IN_SECONDS:86400}
  kafka:
    topics:
      user-password-reset: password-reset-topic
server:
    error:
        include-message: always
        include-binding-errors: always
        include-exception: true
    shutdown: graceful
    servlet:
        context-path: /api

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecom-user}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/master.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
#          jwk-set-uri: http://localhost:8000/user-service/api/.well-known/jwks.json
  jackson:
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true


logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    org.springframework.security: DEBUG
