management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true

ecom:
  client:
    payment-service:
      url: ${PAYMENT_SERVICE_URL:http://localhost:8000/payment-service}/api
    product-service:
      url: ${PRODUCT_SERVICE_URL:http://localhost:8000/product-service}/api
    user-service:
      url: ${USER_SERVICE_URL:http://localhost:8000/user-service}/api
  claims:
    role: ${JWT_CLAIM_ROLE:role}
    userId: ${JWT_CLAIM_USER_ID:userId}
    email: ${JWT_CLAIM_EMAIL:email}
  kafka:
    topics:
      order-placed: order-placed-topic
      payment: payment-topic


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: off
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate.orm.connections.pooling: off
    org.springframework.security: DEBUG


server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  shutdown: graceful
  servlet:
    context-path: /api

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecom-orders}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/master.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8000}
          jwk-set-uri: ${AUTH_JWK_ISSUER_URI:http://localhost:8000/user-service/api}/.well-known/jwks.json
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: cart-service-group
      auto-offset-reset: latest
    properties:
      security.protocol: SSL
      ssl.truststore.type: PEM
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH}
      ssl.keystore.type: PEM
      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH}
