server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  shutdown: graceful
  servlet:
        context-path: /api
spring:
  application:
    name: cart-service

  output:
    ansi:
      enabled: always

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/cartdb?authSource=admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: cart-service-group
      auto-offset-reset: latest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true

ecom:
  client:
    order-service:
      url: ${ORDER_SERVICE_URL:http://localhost:8000/order-service}
    product-service:
      url: ${PRODUCT_SERVICE_URL:http://localhost:8000/product-service}
    user-service:
      url: ${USER_SERVICE_URL:http://localhost:8000/user-service}

  kafka:
    topics:
      order-placed: order-placed-topic
