@startuml
'https://plantuml.com/sequence-diagram


Frontend -> Cart: checkout(\n\taddress,\n\tpaymentMethod\n)

Cart -> Order: createOrder(\n\taddress,\n\tpaymentMethod,\n\tcartItems\n)

Order -> Product: validateStock(\n\tcartItems\n)
opt #pink stock not available
    Product --> Order: stockNotAvailable
    Order --> Cart: error("Out of stock")
    Cart --> Frontend: error("Out of stock")
end
Order -> Order: Generate Order with\n1. Address,\n2. PaymentStatus.Pending,\n3. amount\n

Order -> Payment: generatePaymentLink(\n\torderId,\n\tfinalAmount,\n\tpaymentMethod\n)
opt #pink failed payment link generation
    Payment --> Order: error("Payment link generation failed")
    Order --> Cart: error("Payment link generation failed")
    Cart --> Frontend: error("Payment link generation failed")
end

Payment --> Order: paymentLink
Order --> Cart: Order details along with paymentLink
Cart --> Frontend: paymentLink, orderId

== Payment Gateway Callback ==

"Payment\nGateway" -> Payment: webhook(paymentStatus)
Payment -> Payment: validate webhook

Payment -> Kafka: publish(payment.completed)
Kafka -> Order: consume(payment.completed)
Order -> Order: setStatus(PLACED)
Order -> Kafka: publish(order.placed)

Kafka -> Cart: consume(order.placed)
Cart -> Cart: clearCart()
Kafka -> Notification: consume(order.placed)
Notification -> Frontend: sendOrderConfirmation()
Kafka -> Product: consume(order.placed)
Product -> Product: reduceStock(\n\tcartItems\n)

@enduml